/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestPhotographyRouteImport } from './routes/request-photography'
import { Route as RequestGearRouteImport } from './routes/request-gear'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PhotographerLinkRouteImport } from './routes/photographer-link'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPhotographerLinkRouteImport } from './routes/api.photographer-link'
import { Route as ApiAdminsRouteImport } from './routes/api.admins'
import { Route as AdminTrainingRouteImport } from './routes/admin_.training'
import { Route as AdminTeamRouteImport } from './routes/admin_.team'
import { Route as AdminShotListGeneratorRouteImport } from './routes/admin_.shot-list-generator'
import { Route as AdminShotListBlocksRouteImport } from './routes/admin_.shot-list-blocks'
import { Route as AdminRequestsPhotographyRouteImport } from './routes/admin_.requests-photography'
import { Route as AdminRequestsGearRouteImport } from './routes/admin_.requests-gear'
import { Route as AdminRequestsRouteImport } from './routes/admin_.requests'
import { Route as AdminPhotographersRouteImport } from './routes/admin_.photographers'
import { Route as AdminPhotoRequestsRouteImport } from './routes/admin_.photo-requests'
import { Route as AdminOnboardingRouteImport } from './routes/admin_.onboarding'
import { Route as AdminManageRouteImport } from './routes/admin_.manage'
import { Route as AdminLandingPhotosRouteImport } from './routes/admin_.landing-photos'
import { Route as AdminHistoryRouteImport } from './routes/admin_.history'
import { Route as AdminGearManageRouteImport } from './routes/admin_.gear-manage'
import { Route as AdminGearHistoryRouteImport } from './routes/admin_.gear-history'
import { Route as AdminGearRouteImport } from './routes/admin_.gear'
import { Route as AdminEventsRouteImport } from './routes/admin_.events'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin_.announcements'
import { Route as AdminAdminsRouteImport } from './routes/admin_.admins'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AdminOnboardingTemplatesTemplateIdRouteImport } from './routes/admin_.onboarding_.templates.$templateId'
import { Route as AdminOnboardingPagesSlugRouteImport } from './routes/admin_.onboarding_.pages.$slug'
import { Route as AdminOnboardingHiresHireIdRouteImport } from './routes/admin_.onboarding_.hires.$hireId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPhotographyRoute = RequestPhotographyRouteImport.update({
  id: '/request-photography',
  path: '/request-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestGearRoute = RequestGearRouteImport.update({
  id: '/request-gear',
  path: '/request-gear',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographerLinkRoute = PhotographerLinkRouteImport.update({
  id: '/photographer-link',
  path: '/photographer-link',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotographerLinkRoute = ApiPhotographerLinkRouteImport.update({
  id: '/api/photographer-link',
  path: '/api/photographer-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminsRoute = ApiAdminsRouteImport.update({
  id: '/api/admins',
  path: '/api/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/admin_/training',
  path: '/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin_/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShotListGeneratorRoute = AdminShotListGeneratorRouteImport.update({
  id: '/admin_/shot-list-generator',
  path: '/admin/shot-list-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShotListBlocksRoute = AdminShotListBlocksRouteImport.update({
  id: '/admin_/shot-list-blocks',
  path: '/admin/shot-list-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsPhotographyRoute =
  AdminRequestsPhotographyRouteImport.update({
    id: '/admin_/requests-photography',
    path: '/admin/requests-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsGearRoute = AdminRequestsGearRouteImport.update({
  id: '/admin_/requests-gear',
  path: '/admin/requests-gear',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin_/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotographersRoute = AdminPhotographersRouteImport.update({
  id: '/admin_/photographers',
  path: '/admin/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotoRequestsRoute = AdminPhotoRequestsRouteImport.update({
  id: '/admin_/photo-requests',
  path: '/admin/photo-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/admin_/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/admin_/manage',
  path: '/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPhotosRoute = AdminLandingPhotosRouteImport.update({
  id: '/admin_/landing-photos',
  path: '/admin/landing-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin_/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGearManageRoute = AdminGearManageRouteImport.update({
  id: '/admin_/gear-manage',
  path: '/admin/gear-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGearHistoryRoute = AdminGearHistoryRouteImport.update({
  id: '/admin_/gear-history',
  path: '/admin/gear-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGearRoute = AdminGearRouteImport.update({
  id: '/admin_/gear',
  path: '/admin/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin_/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin_/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin_/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingTemplatesTemplateIdRoute =
  AdminOnboardingTemplatesTemplateIdRouteImport.update({
    id: '/admin_/onboarding_/templates/$templateId',
    path: '/admin/onboarding/templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOnboardingPagesSlugRoute =
  AdminOnboardingPagesSlugRouteImport.update({
    id: '/admin_/onboarding_/pages/$slug',
    path: '/admin/onboarding/pages/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOnboardingHiresHireIdRoute =
  AdminOnboardingHiresHireIdRouteImport.update({
    id: '/admin_/onboarding_/hires/$hireId',
    path: '/admin/onboarding/hires/$hireId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/photographer-link': typeof PhotographerLinkRoute
  '/request': typeof RequestRoute
  '/request-gear': typeof RequestGearRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gear': typeof AdminGearRoute
  '/admin/gear-history': typeof AdminGearHistoryRoute
  '/admin/gear-manage': typeof AdminGearManageRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/landing-photos': typeof AdminLandingPhotosRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/requests-gear': typeof AdminRequestsGearRoute
  '/admin/requests-photography': typeof AdminRequestsPhotographyRoute
  '/admin/shot-list-blocks': typeof AdminShotListBlocksRoute
  '/admin/shot-list-generator': typeof AdminShotListGeneratorRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/training': typeof AdminTrainingRoute
  '/api/admins': typeof ApiAdminsRoute
  '/api/photographer-link': typeof ApiPhotographerLinkRoute
  '/admin/onboarding/hires/$hireId': typeof AdminOnboardingHiresHireIdRoute
  '/admin/onboarding/pages/$slug': typeof AdminOnboardingPagesSlugRoute
  '/admin/onboarding/templates/$templateId': typeof AdminOnboardingTemplatesTemplateIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/photographer-link': typeof PhotographerLinkRoute
  '/request': typeof RequestRoute
  '/request-gear': typeof RequestGearRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gear': typeof AdminGearRoute
  '/admin/gear-history': typeof AdminGearHistoryRoute
  '/admin/gear-manage': typeof AdminGearManageRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/landing-photos': typeof AdminLandingPhotosRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/requests-gear': typeof AdminRequestsGearRoute
  '/admin/requests-photography': typeof AdminRequestsPhotographyRoute
  '/admin/shot-list-blocks': typeof AdminShotListBlocksRoute
  '/admin/shot-list-generator': typeof AdminShotListGeneratorRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/training': typeof AdminTrainingRoute
  '/api/admins': typeof ApiAdminsRoute
  '/api/photographer-link': typeof ApiPhotographerLinkRoute
  '/admin/onboarding/hires/$hireId': typeof AdminOnboardingHiresHireIdRoute
  '/admin/onboarding/pages/$slug': typeof AdminOnboardingPagesSlugRoute
  '/admin/onboarding/templates/$templateId': typeof AdminOnboardingTemplatesTemplateIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/photographer-link': typeof PhotographerLinkRoute
  '/request': typeof RequestRoute
  '/request-gear': typeof RequestGearRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin_/admins': typeof AdminAdminsRoute
  '/admin_/announcements': typeof AdminAnnouncementsRoute
  '/admin_/events': typeof AdminEventsRoute
  '/admin_/gear': typeof AdminGearRoute
  '/admin_/gear-history': typeof AdminGearHistoryRoute
  '/admin_/gear-manage': typeof AdminGearManageRoute
  '/admin_/history': typeof AdminHistoryRoute
  '/admin_/landing-photos': typeof AdminLandingPhotosRoute
  '/admin_/manage': typeof AdminManageRoute
  '/admin_/onboarding': typeof AdminOnboardingRoute
  '/admin_/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin_/photographers': typeof AdminPhotographersRoute
  '/admin_/requests': typeof AdminRequestsRoute
  '/admin_/requests-gear': typeof AdminRequestsGearRoute
  '/admin_/requests-photography': typeof AdminRequestsPhotographyRoute
  '/admin_/shot-list-blocks': typeof AdminShotListBlocksRoute
  '/admin_/shot-list-generator': typeof AdminShotListGeneratorRoute
  '/admin_/team': typeof AdminTeamRoute
  '/admin_/training': typeof AdminTrainingRoute
  '/api/admins': typeof ApiAdminsRoute
  '/api/photographer-link': typeof ApiPhotographerLinkRoute
  '/admin_/onboarding_/hires/$hireId': typeof AdminOnboardingHiresHireIdRoute
  '/admin_/onboarding_/pages/$slug': typeof AdminOnboardingPagesSlugRoute
  '/admin_/onboarding_/templates/$templateId': typeof AdminOnboardingTemplatesTemplateIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/photographer-link'
    | '/request'
    | '/request-gear'
    | '/request-photography'
    | '/reset-password'
    | '/admin/admins'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/gear'
    | '/admin/gear-history'
    | '/admin/gear-manage'
    | '/admin/history'
    | '/admin/landing-photos'
    | '/admin/manage'
    | '/admin/onboarding'
    | '/admin/photo-requests'
    | '/admin/photographers'
    | '/admin/requests'
    | '/admin/requests-gear'
    | '/admin/requests-photography'
    | '/admin/shot-list-blocks'
    | '/admin/shot-list-generator'
    | '/admin/team'
    | '/admin/training'
    | '/api/admins'
    | '/api/photographer-link'
    | '/admin/onboarding/hires/$hireId'
    | '/admin/onboarding/pages/$slug'
    | '/admin/onboarding/templates/$templateId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/photographer-link'
    | '/request'
    | '/request-gear'
    | '/request-photography'
    | '/reset-password'
    | '/admin/admins'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/gear'
    | '/admin/gear-history'
    | '/admin/gear-manage'
    | '/admin/history'
    | '/admin/landing-photos'
    | '/admin/manage'
    | '/admin/onboarding'
    | '/admin/photo-requests'
    | '/admin/photographers'
    | '/admin/requests'
    | '/admin/requests-gear'
    | '/admin/requests-photography'
    | '/admin/shot-list-blocks'
    | '/admin/shot-list-generator'
    | '/admin/team'
    | '/admin/training'
    | '/api/admins'
    | '/api/photographer-link'
    | '/admin/onboarding/hires/$hireId'
    | '/admin/onboarding/pages/$slug'
    | '/admin/onboarding/templates/$templateId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/photographer-link'
    | '/request'
    | '/request-gear'
    | '/request-photography'
    | '/reset-password'
    | '/admin_/admins'
    | '/admin_/announcements'
    | '/admin_/events'
    | '/admin_/gear'
    | '/admin_/gear-history'
    | '/admin_/gear-manage'
    | '/admin_/history'
    | '/admin_/landing-photos'
    | '/admin_/manage'
    | '/admin_/onboarding'
    | '/admin_/photo-requests'
    | '/admin_/photographers'
    | '/admin_/requests'
    | '/admin_/requests-gear'
    | '/admin_/requests-photography'
    | '/admin_/shot-list-blocks'
    | '/admin_/shot-list-generator'
    | '/admin_/team'
    | '/admin_/training'
    | '/api/admins'
    | '/api/photographer-link'
    | '/admin_/onboarding_/hires/$hireId'
    | '/admin_/onboarding_/pages/$slug'
    | '/admin_/onboarding_/templates/$templateId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PhotographerLinkRoute: typeof PhotographerLinkRoute
  RequestRoute: typeof RequestRoute
  RequestGearRoute: typeof RequestGearRoute
  RequestPhotographyRoute: typeof RequestPhotographyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGearRoute: typeof AdminGearRoute
  AdminGearHistoryRoute: typeof AdminGearHistoryRoute
  AdminGearManageRoute: typeof AdminGearManageRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLandingPhotosRoute: typeof AdminLandingPhotosRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPhotoRequestsRoute: typeof AdminPhotoRequestsRoute
  AdminPhotographersRoute: typeof AdminPhotographersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminRequestsGearRoute: typeof AdminRequestsGearRoute
  AdminRequestsPhotographyRoute: typeof AdminRequestsPhotographyRoute
  AdminShotListBlocksRoute: typeof AdminShotListBlocksRoute
  AdminShotListGeneratorRoute: typeof AdminShotListGeneratorRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  ApiAdminsRoute: typeof ApiAdminsRoute
  ApiPhotographerLinkRoute: typeof ApiPhotographerLinkRoute
  AdminOnboardingHiresHireIdRoute: typeof AdminOnboardingHiresHireIdRoute
  AdminOnboardingPagesSlugRoute: typeof AdminOnboardingPagesSlugRoute
  AdminOnboardingTemplatesTemplateIdRoute: typeof AdminOnboardingTemplatesTemplateIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-photography': {
      id: '/request-photography'
      path: '/request-photography'
      fullPath: '/request-photography'
      preLoaderRoute: typeof RequestPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-gear': {
      id: '/request-gear'
      path: '/request-gear'
      fullPath: '/request-gear'
      preLoaderRoute: typeof RequestGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographer-link': {
      id: '/photographer-link'
      path: '/photographer-link'
      fullPath: '/photographer-link'
      preLoaderRoute: typeof PhotographerLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photographer-link': {
      id: '/api/photographer-link'
      path: '/api/photographer-link'
      fullPath: '/api/photographer-link'
      preLoaderRoute: typeof ApiPhotographerLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admins': {
      id: '/api/admins'
      path: '/api/admins'
      fullPath: '/api/admins'
      preLoaderRoute: typeof ApiAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/training': {
      id: '/admin_/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/team': {
      id: '/admin_/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/shot-list-generator': {
      id: '/admin_/shot-list-generator'
      path: '/admin/shot-list-generator'
      fullPath: '/admin/shot-list-generator'
      preLoaderRoute: typeof AdminShotListGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/shot-list-blocks': {
      id: '/admin_/shot-list-blocks'
      path: '/admin/shot-list-blocks'
      fullPath: '/admin/shot-list-blocks'
      preLoaderRoute: typeof AdminShotListBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/requests-photography': {
      id: '/admin_/requests-photography'
      path: '/admin/requests-photography'
      fullPath: '/admin/requests-photography'
      preLoaderRoute: typeof AdminRequestsPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/requests-gear': {
      id: '/admin_/requests-gear'
      path: '/admin/requests-gear'
      fullPath: '/admin/requests-gear'
      preLoaderRoute: typeof AdminRequestsGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/requests': {
      id: '/admin_/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/photographers': {
      id: '/admin_/photographers'
      path: '/admin/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof AdminPhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/photo-requests': {
      id: '/admin_/photo-requests'
      path: '/admin/photo-requests'
      fullPath: '/admin/photo-requests'
      preLoaderRoute: typeof AdminPhotoRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/onboarding': {
      id: '/admin_/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/manage': {
      id: '/admin_/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/landing-photos': {
      id: '/admin_/landing-photos'
      path: '/admin/landing-photos'
      fullPath: '/admin/landing-photos'
      preLoaderRoute: typeof AdminLandingPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/history': {
      id: '/admin_/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/gear-manage': {
      id: '/admin_/gear-manage'
      path: '/admin/gear-manage'
      fullPath: '/admin/gear-manage'
      preLoaderRoute: typeof AdminGearManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/gear-history': {
      id: '/admin_/gear-history'
      path: '/admin/gear-history'
      fullPath: '/admin/gear-history'
      preLoaderRoute: typeof AdminGearHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/gear': {
      id: '/admin_/gear'
      path: '/admin/gear'
      fullPath: '/admin/gear'
      preLoaderRoute: typeof AdminGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/events': {
      id: '/admin_/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/announcements': {
      id: '/admin_/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/admins': {
      id: '/admin_/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/onboarding_/templates/$templateId': {
      id: '/admin_/onboarding_/templates/$templateId'
      path: '/admin/onboarding/templates/$templateId'
      fullPath: '/admin/onboarding/templates/$templateId'
      preLoaderRoute: typeof AdminOnboardingTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/onboarding_/pages/$slug': {
      id: '/admin_/onboarding_/pages/$slug'
      path: '/admin/onboarding/pages/$slug'
      fullPath: '/admin/onboarding/pages/$slug'
      preLoaderRoute: typeof AdminOnboardingPagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/onboarding_/hires/$hireId': {
      id: '/admin_/onboarding_/hires/$hireId'
      path: '/admin/onboarding/hires/$hireId'
      fullPath: '/admin/onboarding/hires/$hireId'
      preLoaderRoute: typeof AdminOnboardingHiresHireIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PhotographerLinkRoute: PhotographerLinkRoute,
  RequestRoute: RequestRoute,
  RequestGearRoute: RequestGearRoute,
  RequestPhotographyRoute: RequestPhotographyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGearRoute: AdminGearRoute,
  AdminGearHistoryRoute: AdminGearHistoryRoute,
  AdminGearManageRoute: AdminGearManageRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLandingPhotosRoute: AdminLandingPhotosRoute,
  AdminManageRoute: AdminManageRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPhotoRequestsRoute: AdminPhotoRequestsRoute,
  AdminPhotographersRoute: AdminPhotographersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminRequestsGearRoute: AdminRequestsGearRoute,
  AdminRequestsPhotographyRoute: AdminRequestsPhotographyRoute,
  AdminShotListBlocksRoute: AdminShotListBlocksRoute,
  AdminShotListGeneratorRoute: AdminShotListGeneratorRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  ApiAdminsRoute: ApiAdminsRoute,
  ApiPhotographerLinkRoute: ApiPhotographerLinkRoute,
  AdminOnboardingHiresHireIdRoute: AdminOnboardingHiresHireIdRoute,
  AdminOnboardingPagesSlugRoute: AdminOnboardingPagesSlugRoute,
  AdminOnboardingTemplatesTemplateIdRoute:
    AdminOnboardingTemplatesTemplateIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
