/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestPhotographyRouteImport } from './routes/request-photography'
import { Route as RequestRouteImport } from './routes/request'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminsRouteImport } from './routes/api.admins'
import { Route as AdminRequestsRouteImport } from './routes/admin_.requests'
import { Route as AdminPhotoRequestsRouteImport } from './routes/admin_.photo-requests'
import { Route as AdminManageRouteImport } from './routes/admin_.manage'
import { Route as AdminHistoryRouteImport } from './routes/admin_.history'
import { Route as AdminAdminsRouteImport } from './routes/admin_.admins'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPhotographyRoute = RequestPhotographyRouteImport.update({
  id: '/request-photography',
  path: '/request-photography',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminsRoute = ApiAdminsRouteImport.update({
  id: '/api/admins',
  path: '/api/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin_/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotoRequestsRoute = AdminPhotoRequestsRouteImport.update({
  id: '/admin_/photo-requests',
  path: '/admin/photo-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/admin_/manage',
  path: '/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin_/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin_/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/request': typeof RequestRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/api/admins': typeof ApiAdminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/request': typeof RequestRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/api/admins': typeof ApiAdminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/request': typeof RequestRoute
  '/request-photography': typeof RequestPhotographyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin_/admins': typeof AdminAdminsRoute
  '/admin_/history': typeof AdminHistoryRoute
  '/admin_/manage': typeof AdminManageRoute
  '/admin_/photo-requests': typeof AdminPhotoRequestsRoute
  '/admin_/requests': typeof AdminRequestsRoute
  '/api/admins': typeof ApiAdminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/request'
    | '/request-photography'
    | '/reset-password'
    | '/admin/admins'
    | '/admin/history'
    | '/admin/manage'
    | '/admin/photo-requests'
    | '/admin/requests'
    | '/api/admins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/request'
    | '/request-photography'
    | '/reset-password'
    | '/admin/admins'
    | '/admin/history'
    | '/admin/manage'
    | '/admin/photo-requests'
    | '/admin/requests'
    | '/api/admins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/request'
    | '/request-photography'
    | '/reset-password'
    | '/admin_/admins'
    | '/admin_/history'
    | '/admin_/manage'
    | '/admin_/photo-requests'
    | '/admin_/requests'
    | '/api/admins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  RequestRoute: typeof RequestRoute
  RequestPhotographyRoute: typeof RequestPhotographyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminPhotoRequestsRoute: typeof AdminPhotoRequestsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  ApiAdminsRoute: typeof ApiAdminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-photography': {
      id: '/request-photography'
      path: '/request-photography'
      fullPath: '/request-photography'
      preLoaderRoute: typeof RequestPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admins': {
      id: '/api/admins'
      path: '/api/admins'
      fullPath: '/api/admins'
      preLoaderRoute: typeof ApiAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/requests': {
      id: '/admin_/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/photo-requests': {
      id: '/admin_/photo-requests'
      path: '/admin/photo-requests'
      fullPath: '/admin/photo-requests'
      preLoaderRoute: typeof AdminPhotoRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/manage': {
      id: '/admin_/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/history': {
      id: '/admin_/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/admins': {
      id: '/admin_/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  RequestRoute: RequestRoute,
  RequestPhotographyRoute: RequestPhotographyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminManageRoute: AdminManageRoute,
  AdminPhotoRequestsRoute: AdminPhotoRequestsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  ApiAdminsRoute: ApiAdminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
